//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using SubstrateNetApi.Model.Types.TypeDefArray;
using SubstrateNetApi.Model.Types.TypeDefComposite;
using SubstrateNetApi.Model.Types.TypeDefVariant;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.Types.TypeDefVariant
{
    
    
    public enum MultiAddress
    {
        
        Id,
        
        Index,
        
        Raw,
        
        Address32,
        
        Address20,
    }
    
    public sealed class EnumMultiAddress : BaseEnumExt<MultiAddress, AccountId32, BaseCom<U32>, BaseVec<U8>, Arr32U8, Arr20U8>
    {
    }
}
