//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using SubstrateNetApi.Model.Types.TypeDefArray;
using SubstrateNetApi.Model.Types.TypeDefComposite;
using SubstrateNetApi.Model.Types.TypeDefVariant;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.Types.TypeDefComposite
{
    
    
    public sealed class DeletedContract : BaseType
    {
        
        private BaseVec<U8> _trieId;
        
        public BaseVec<U8> TrieId
        {
            get
            {
                return this._trieId;
            }
            set
            {
                this._trieId = value;
            }
        }
        
        public override string TypeName()
        {
            return "DeletedContract";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(TrieId.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            TrieId = new BaseVec<U8>();
            TrieId.Decode(byteArray, ref p);
            _typeSize = p - start;
        }
    }
}
