//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using SubstrateNetApi.Model.Types.TypeDefArray;
using SubstrateNetApi.Model.Types.TypeDefComposite;
using SubstrateNetApi.Model.Types.TypeDefVariant;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.Types.TypeDefComposite
{
    
    
    public sealed class EquivocationProof : BaseType
    {
        
        private U64 _setId;
        
        private EnumEquivocation _equivocation;
        
        public U64 SetId
        {
            get
            {
                return this._setId;
            }
            set
            {
                this._setId = value;
            }
        }
        
        public EnumEquivocation Equivocation
        {
            get
            {
                return this._equivocation;
            }
            set
            {
                this._equivocation = value;
            }
        }
        
        public override string TypeName()
        {
            return "EquivocationProof";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(SetId.Encode());
            result.AddRange(Equivocation.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            SetId = new U64();
            SetId.Decode(byteArray, ref p);
            Equivocation = new EnumEquivocation();
            Equivocation.Decode(byteArray, ref p);
            _typeSize = p - start;
        }
    }
}
