//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using SubstrateNetApi.Model.Types.TypeDefArray;
using SubstrateNetApi.Model.Types.TypeDefComposite;
using SubstrateNetApi.Model.Types.TypeDefVariant;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.Types.TypeDefComposite
{
    
    
    public sealed class RuntimeDbWeight : BaseType
    {
        
        private U64 _read;
        
        private U64 _write;
        
        public U64 Read
        {
            get
            {
                return this._read;
            }
            set
            {
                this._read = value;
            }
        }
        
        public U64 Write
        {
            get
            {
                return this._write;
            }
            set
            {
                this._write = value;
            }
        }
        
        public override string TypeName()
        {
            return "RuntimeDbWeight";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Read.Encode());
            result.AddRange(Write.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Read = new U64();
            Read.Decode(byteArray, ref p);
            Write = new U64();
            Write.Decode(byteArray, ref p);
            _typeSize = p - start;
        }
    }
}
