//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using SubstrateNetApi.Model.Types.TypeDefArray;
using SubstrateNetApi.Model.Types.TypeDefComposite;
using SubstrateNetApi.Model.Types.TypeDefVariant;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.Types.TypeDefComposite
{
    
    
    public sealed class TransactionStorageProof : BaseType
    {
        
        private BaseVec<U8> _chunk;
        
        private BaseVec<BaseVec<U8>> _proof;
        
        public BaseVec<U8> Chunk
        {
            get
            {
                return this._chunk;
            }
            set
            {
                this._chunk = value;
            }
        }
        
        public BaseVec<BaseVec<U8>> Proof
        {
            get
            {
                return this._proof;
            }
            set
            {
                this._proof = value;
            }
        }
        
        public override string TypeName()
        {
            return "TransactionStorageProof";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Chunk.Encode());
            result.AddRange(Proof.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Chunk = new BaseVec<U8>();
            Chunk.Decode(byteArray, ref p);
            Proof = new BaseVec<BaseVec<U8>>();
            Proof.Decode(byteArray, ref p);
            _typeSize = p - start;
        }
    }
}
