//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using SubstrateNetApi.Model.Types.TypeDefArray;
using SubstrateNetApi.Model.Types.TypeDefComposite;
using SubstrateNetApi.Model.Types.TypeDefVariant;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.Types.TypeDefComposite
{
    
    
    public sealed class UnlockChunk : BaseType
    {
        
        private BaseCom<U128> _value;
        
        private BaseCom<U32> _era;
        
        public BaseCom<U128> Value
        {
            get
            {
                return this._value;
            }
            set
            {
                this._value = value;
            }
        }
        
        public BaseCom<U32> Era
        {
            get
            {
                return this._era;
            }
            set
            {
                this._era = value;
            }
        }
        
        public override string TypeName()
        {
            return "UnlockChunk";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Value.Encode());
            result.AddRange(Era.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Value = new BaseCom<U128>();
            Value.Decode(byteArray, ref p);
            Era = new BaseCom<U32>();
            Era.Decode(byteArray, ref p);
            _typeSize = p - start;
        }
    }
}
