//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using SubstrateNetApi.Model.Types.TypeDefArray;
using SubstrateNetApi.Model.Types.TypeDefComposite;
using SubstrateNetApi.Model.Types.TypeDefVariant;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.Custom.Events
{
    
    
    /// <summary>
    /// >> Path: frame_system.pallet.Event
    /// Event for the System pallet.
    /// </summary>
    public sealed class FrameSystem
    {
    }
    
    /// <summary>
    /// >> Event: ExtrinsicSuccess
    /// Event for the System pallet.
    /// </summary>
    public sealed class ExtrinsicSuccess
    {
    }
    
    /// <summary>
    /// >> Event: ExtrinsicFailed
    /// Event for the System pallet.
    /// </summary>
    public sealed class ExtrinsicFailed
    {
    }
    
    /// <summary>
    /// >> Event: CodeUpdated
    /// Event for the System pallet.
    /// </summary>
    public sealed class CodeUpdated
    {
    }
    
    /// <summary>
    /// >> Event: NewAccount
    /// Event for the System pallet.
    /// </summary>
    public sealed class NewAccount
    {
    }
    
    /// <summary>
    /// >> Event: KilledAccount
    /// Event for the System pallet.
    /// </summary>
    public sealed class KilledAccount
    {
    }
    
    /// <summary>
    /// >> Event: Remarked
    /// Event for the System pallet.
    /// </summary>
    public sealed class Remarked
    {
    }
}
