//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SubstrateNetApi.Model.Types.Base;
using SubstrateNetApi.Model.Types.Primitive;
using SubstrateNetApi.Model.Types.TypeDefArray;
using SubstrateNetApi.Model.Types.TypeDefComposite;
using SubstrateNetApi.Model.Types.TypeDefVariant;
using System;
using System.Collections.Generic;


namespace SubstrateNetApi.Model.Custom.Events
{
    
    
    /// <summary>
    /// >> Path: pallet_scheduler.pallet.Event
    /// Events type.
    /// </summary>
    public sealed class PalletScheduler
    {
    }
    
    /// <summary>
    /// >> Event: Scheduled
    /// Events type.
    /// </summary>
    public sealed class Scheduled
    {
    }
    
    /// <summary>
    /// >> Event: Canceled
    /// Events type.
    /// </summary>
    public sealed class Canceled
    {
    }
    
    /// <summary>
    /// >> Event: Dispatched
    /// Events type.
    /// </summary>
    public sealed class Dispatched
    {
    }
}
